const ESC50: Record<string, [string, string]> = {
  dog: ["🐕", "Chien"],
  rain: ["🌧️", "Pluie"],
  crying_baby: ["👶", "Bébé qui pleure"],
  door_wood_knock: ["🚪", "Coup à la porte"],
  helicopter: ["🚁", "Hélicoptère"],
  rooster: ["🐓", "Coq"],
  sea_waves: ["🌊", "Vagues"],
  sneezing: ["🤧", "Éternuement"],
  mouse_click: ["🖱️", "Clic de souris"],
  chainsaw: ["🪚", "Tronçonneuse"],
  pig: ["🐷", "Cochon"],
  crackling_fire: ["🔥", "Feu crépitant"],
  clapping: ["👏", "Applaudissements"],
  keyboard_typing: ["⌨️", "Frappe au clavier"],
  siren: ["🚨", "Sirène"],
  cow: ["🐄", "Vache"],
  crickets: ["🦗", "Grillons"],
  breathing: ["💨", "Respiration"],
  door_wood_creaks: ["🚪", "Porte qui grince"],
  car_horn: ["📯", "Klaxon"],
  frog: ["🐸", "Grenouille"],
  chirping_birds: ["🐦", "Chants d'oiseaux"],
  coughing: ["😷", "Toux"],
  can_opening: ["🥫", "Ouverture de canette"],
  engine: ["🚗", "Moteur"],
  cat: ["🐱", "Chat"],
  water_drops: ["💧", "Gouttes d'eau"],
  footsteps: ["👣", "Pas"],
  washing_machine: ["🧺", "Machine à laver"],
  train: ["🚂", "Train"],
  hen: ["🐔", "Poule"],
  wind: ["🌬️", "Vent"],
  laughing: ["😂", "Rire"],
  vacuum_cleaner: ["🧹", "Aspirateur"],
  church_bells: ["🔔", "Cloches d'église"],
  insects: ["🦟", "Insectes"],
  pouring_water: ["🚰", "Eau versée"],
  brushing_teeth: ["🪥", "Brossage de dents"],
  clock_alarm: ["⏰", "Réveil"],
  airplane: ["✈️", "Avion"],
  sheep: ["🐑", "Mouton"],
  toilet_flush: ["🚽", "Chasse d'eau"],
  snoring: ["😴", "Ronflement"],
  clock_tick: ["⏱️", "Tic-tac"],
  fireworks: ["🎆", "Feux d'artifice"],
  crow: ["🐦‍⬛", "Corbeau"],
  thunderstorm: ["⛈️", "Orage"],
  drinking_sipping: ["🥤", "Gorgée"],
  glass_breaking: ["💥", "Verre brisé"],
  hand_saw: ["🪚", "Scie à main"],
};

export const getClassInfo = (name: string) => {
  const [emoji, label] = ESC50[name] ?? ["🔈", name.replaceAll("_", " ")];
  return { emoji, label };
};
